make: fix SDL/SDL_net linking
fixes:

g++ -Wall  main.cpp ipxserver.cpp -lSDL_net -o ipxnet
ipxserver.cpp: In function ‘void ackClient(IPaddress)’:
ipxserver.cpp:118:8: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
   Bits result;
        ^
/usr/bin/ld: /tmp/cc2wjllH.o: undefined reference to symbol 'SDL_GetError'
//usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'ipxnet' failed
make: *** [ipxnet] Error 1